### PR TITLE
Get users API

### PR DESCRIPTION
**Pull request by InfiniteCoder01**
Really useful for getting self user_id for API calls, where id is different from broadcaster_id

### CODE REVIEW

**Comment by Owlkaline** [comment]
Additionally, at the moment if you set the client id to a different account than the broadcaster id, it doesn't work as far as I am aware and is a feature that I have to still work out how to do.

So the whole "this_user"/"this_account" thing is just using broadcaster_id in everycase which makes it redundant.

The get_user endpoint is a useful to get the broadcaster_id which I will be able to use to have it grab it automatically instead of making the user put it in now/in future.

If you currently have an example of where this_account_id is a different account to the broadcasters_id's channel and it is able to receive events/send messages in not their own channel that would be nice to see. Since as far as I am aware that isn't possible.

**Comment by InfiniteCoder01** [comment]
Only some events from eventsub are limited to only broadcaster account. Others can be accessible by moderators. 
What is useful - being able to interact with TwitchAPI's as a moderator, to explicitly show, for example:
"SuperCoolBot gave Owlkaline a shoutout"
"Message was deleted by SuperCoolBot"
"TwitchScamsU4 was banned by SuperCoolBot"
+ Sending messages as bot, but this can already be done via IRC (couldn't get it to work tho, even after hooking up Godot settings to it)

As for the PR, it works for sure. Wrote and tested it live on stream

**Comment by Owlkaline** [comment]
> Only some events from eventsub are limited to only broadcaster account. Others can be accessible by moderators. What is useful - being able to interact with TwitchAPIs as a moderator, to explicitly show, for example: "SuperCoolBot gave Owlkaline a shoutout" "Message was deleted by SuperCoolBot" "TwitchScamsU4 was banned by SuperCoolBot"
> 
>     * Sending messages as bot, but this can already be done via IRC (couldn't get it to work tho, even after hooking up Godot settings to it)
> 
> 
> As for the PR, it works for sure. Wrote and tested it live on stream

Yes, I am aware, how do you get the bot to use the api though? 

Do you just create it without subscribing to any twitch events?
So that it doesn't generate twitch event permissions that it is unable to give to that user.

Because the twitch api spec for the api for deleting messages says the following about moderator id:

The ID of the broadcaster or a user that has permission to moderate the broadcaster’s chat room. This ID must match the user ID in the user access token.

And currently, if I just put the bot client id / secret in then it fails to create the key because of twitch authentication issues.

At any rate, if you don't mind could you please separate the get_user api stuff from the "this_user" stuff / bot things, since get_user endpoint is ready to be merged no problem, that would be great. 

If it does work like I am guessing above, I know a far better solution that won't require running everything twice
.

**Comment by InfiniteCoder01** [comment]
I made it work (by just duplicating the node in Godot), because I've decided (for some reason) to use bot account for all subscriptions, except ones where I need broadcaster account. Why I want everything to be doubled? Not only I have my chat bot and overlay on this thing, it's also my chat client, which means I want to be able to send messages as a broadcaster in my chat from it (and maybe in future ban and delete messages as a broadcaster). Which makes me want just two APIs, it's just easier at this point.

I am gonna try to separate it

**Comment by Owlkaline** [comment]
> I made it work (by just duplicating the node in Godot), because I've decided (for some reason) to use bot account for all subscriptions, except ones where I need broadcaster account. Why I want everything to be doubled? Not only I have my chat bot and overlay on this thing, it's also my chat client, which means I want to be able to send messages as a broadcaster in my chat from it (and maybe in future ban and delete messages as a broadcaster). Which makes me want just two APIs, it's just easier at this point.
> 
> I am gonna try to separate it

I was unclear sorry, this feature of using broadcaster account and being able to use a bot account to do actions that is a planned feature, I just don't understand how you got it to work with how it works currently using a bot account, since when I have attempted it fails at the code generation step (when you have to authorise via website).

I believe I have a solution that doesn't require running the twitch library twice.

Thanks!

**Comment by InfiniteCoder01** [comment]
Separated. It seems to build, but please check, I'm not that good at git to be sure I've done everything right

**Pull request merged**
